export const ROUTERS = {
    USER: {
        HOME: "/",
        PROFILE: "/profile",
        PRODUCTS: "/products",
        PRODUCTDETAILS: "/product-details",
        LOGIN: "/login",
        NEWS: "/news",
        NEWSDETAILS: "/news-details",
        PAYMENTDETAIL: "/payment-detail",
        PAYMENTFAILED: "/reject",
        PAYMENTSUCCESSFUL: "/confirm",
        CART: "/cart",
        ORDERS: "/orders",
        ORDERDETAILS: "/order-details",
        REGISTER: "/register",
        CHECKOUT: "/checkout",
    },
    ADMIN: {
        HOME: "/admin",
        PRODUCTS: "/admin/products",
        PRODUCTDETAILS: "/admin/product-details",
        NEWS: "/admin/news",
        NEWSDETAILS: "/admin/news-details",
        ORDERS: "/admin/orders",
        ORDERDETAILS: "/admin/order-details",
        USERS: "/admin/users",
        USERDETAILS: "/admin/user-details",
        LOGIN: "/admin/login",
        REGISTER: "/admin/register",
    }
};
